<a href="https://colab.research.google.com/github/himu0023/GEN-AI/blob/main/NLP/LSMT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pip install --upgrade tensorflow

In [1]:
text ="""Data analysis is not just a mere process; it's a tool that empowers
organizations to make informed decisions, predict trends, and improve operational efficiency.
It's the backbone of strategic planning in businesses, governments, and other
organizations.Consider some examples. Take, for instance, a leading e-commerce
company. Through data analysis, the company can understand their customers'
buying behavior, preferences, and patterns. They can then use this information
to personalize customer experiences, forecast sales, and optimize marketing
strategies, ultimately driving business growth and customer satisfaction.
Another good example is the healthcare industry. Through data analysis,
healthcare providers can predict disease outbreaks, improve patient care, and
make informed decisions about treatment strategies. """

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
# Initiate the Tokenizer

tokenizer = Tokenizer()

tokenizer.fit_on_texts([text])

In [4]:
len(tokenizer.word_index)

81

In [5]:
for sentence in text.split('.'):
  print(tokenizer.texts_to_sequences([sentence])[0])

[2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27, 9, 10, 11, 12, 13, 14, 28, 1, 15, 29, 30]
[8, 5, 31, 32, 33, 34, 35, 36, 37, 1, 38, 9]
[39, 40, 41]
[42, 43, 44, 4, 45, 46, 47, 16]
[17, 2, 3, 5, 16, 6, 48, 49, 50, 51, 52, 53, 1, 54]
[55, 6, 56, 57, 58, 59, 10, 60, 18, 61, 62, 63, 1, 64, 65, 19, 66, 67, 68, 69, 1, 18, 70]
[71, 72, 73, 7, 5, 20, 74]
[17, 2, 3, 20, 75, 6, 14, 76, 77, 15, 78, 79, 1, 11, 12, 13, 80, 81, 19]
[]


In [6]:
input_squences=[]

for sentence in text.split('.'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1, len(tokenized_sentence)):
      input_squences.append(tokenized_sentence[:i+1])

In [7]:
input_squences

[[2, 3],
 [2, 3, 7],
 [2, 3, 7, 21],
 [2, 3, 7, 21, 22],
 [2, 3, 7, 21, 22, 4],
 [2, 3, 7, 21, 22, 4, 23],
 [2, 3, 7, 21, 22, 4, 23, 24],
 [2, 3, 7, 21, 22, 4, 23, 24, 8],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27, 9],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27, 9, 10],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27, 9, 10, 11],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27, 9, 10, 11, 12],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27, 9, 10, 11, 12, 13],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27, 9, 10, 11, 12, 13, 14],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27, 9, 10, 11, 12, 13, 14, 28],
 [2, 3, 7, 21, 22, 4, 23, 24, 8, 4, 25, 26, 27, 9, 10, 11, 12, 13, 14, 28, 1],
 [2,
  3,
  7,
  21,
  22,
  4,
  23,
  24,
  8,
  4,
  25,
  26,
  27,
  9,
  10,
  11,
  12,
  13,
  14,
  28,
  1,
  15],
 [2,

In [8]:
max_len = max([len(x) for x in input_squences])

In [9]:
max_len

24

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
paded_input_squences = pad_sequences(input_squences, maxlen=max_len, padding='pre')

In [11]:
paded_input_squences

array([[ 0,  0,  0, ...,  0,  2,  3],
       [ 0,  0,  0, ...,  2,  3,  7],
       [ 0,  0,  0, ...,  3,  7, 21],
       ...,
       [ 0,  0,  0, ..., 12, 13, 80],
       [ 0,  0,  0, ..., 13, 80, 81],
       [ 0,  0,  0, ..., 80, 81, 19]], dtype=int32)

In [12]:
X = paded_input_squences[:,:-1]
y = paded_input_squences[:,-1]

In [13]:
X

array([[ 0,  0,  0, ...,  0,  0,  2],
       [ 0,  0,  0, ...,  0,  2,  3],
       [ 0,  0,  0, ...,  2,  3,  7],
       ...,
       [ 0,  0,  0, ..., 11, 12, 13],
       [ 0,  0,  0, ..., 12, 13, 80],
       [ 0,  0,  0, ..., 13, 80, 81]], dtype=int32)

In [14]:
y

array([ 3,  7, 21, 22,  4, 23, 24,  8,  4, 25, 26, 27,  9, 10, 11, 12, 13,
       14, 28,  1, 15, 29, 30,  5, 31, 32, 33, 34, 35, 36, 37,  1, 38,  9,
       40, 41, 43, 44,  4, 45, 46, 47, 16,  2,  3,  5, 16,  6, 48, 49, 50,
       51, 52, 53,  1, 54,  6, 56, 57, 58, 59, 10, 60, 18, 61, 62, 63,  1,
       64, 65, 19, 66, 67, 68, 69,  1, 18, 70, 72, 73,  7,  5, 20, 74,  2,
        3, 20, 75,  6, 14, 76, 77, 15, 78, 79,  1, 11, 12, 13, 80, 81, 19],
      dtype=int32)

In [15]:
tokenizer.word_index

{'and': 1,
 'data': 2,
 'analysis': 3,
 'a': 4,
 'the': 5,
 'can': 6,
 'is': 7,
 "it's": 8,
 'organizations': 9,
 'to': 10,
 'make': 11,
 'informed': 12,
 'decisions': 13,
 'predict': 14,
 'improve': 15,
 'company': 16,
 'through': 17,
 'customer': 18,
 'strategies': 19,
 'healthcare': 20,
 'not': 21,
 'just': 22,
 'mere': 23,
 'process': 24,
 'tool': 25,
 'that': 26,
 'empowers': 27,
 'trends': 28,
 'operational': 29,
 'efficiency': 30,
 'backbone': 31,
 'of': 32,
 'strategic': 33,
 'planning': 34,
 'in': 35,
 'businesses': 36,
 'governments': 37,
 'other': 38,
 'consider': 39,
 'some': 40,
 'examples': 41,
 'take': 42,
 'for': 43,
 'instance': 44,
 'leading': 45,
 'e': 46,
 'commerce': 47,
 'understand': 48,
 'their': 49,
 "customers'": 50,
 'buying': 51,
 'behavior': 52,
 'preferences': 53,
 'patterns': 54,
 'they': 55,
 'then': 56,
 'use': 57,
 'this': 58,
 'information': 59,
 'personalize': 60,
 'experiences': 61,
 'forecast': 62,
 'sales': 63,
 'optimize': 64,
 'marketing': 65,
 

In [16]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=len(tokenizer.word_index)+1)

In [17]:
y.shape

(102, 82)

In [18]:
X.shape

(102, 23)

### Model Building

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [20]:
model = Sequential()
model.add(Embedding(input_dim=83, output_dim=100))
model.add(LSTM(150))
model.add(Dense(82, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

history = model.fit(X_train, y_train,
                   epochs=100,
                   validation_data=(X_test, y_test),
                   verbose=1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 268ms/step - accuracy: 0.0280 - loss: 4.4077 - val_accuracy: 0.0000e+00 - val_loss: 4.4082
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.0716 - loss: 4.3905 - val_accuracy: 0.0000e+00 - val_loss: 4.4069
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.0465 - loss: 4.3745 - val_accuracy: 0.0000e+00 - val_loss: 4.4048
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.0559 - loss: 4.3433 - val_accuracy: 0.0000e+00 - val_loss: 4.4154
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 136ms/step - accuracy: 0.0459 - loss: 4.2687 - val_accuracy: 0.0000e+00 - val_loss: 4.5598
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 159ms/step - accuracy: 0.0280 - loss: 4.2360 - val_accuracy: 0.0000e+00 - val_loss: 4.6190
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.0364 - loss: 4.1821 - val_accuracy: 0.0952 - val_loss: 4.6624
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.0520 - loss: 4.1006 - val

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 23, 100)        │         8,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 82)             │        12,382 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 513,848 (1.96 MB)

 Trainable params: 171,282 (669.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 342,566 (1.31 MB)

#### *Test the model*

In [23]:
text2= "Data"

# Tokenizer
token_text = tokenizer.texts_to_sequences([text2])[0]

# Padding
padded_text = pad_sequences([token_text], maxlen=max_len-1, padding='pre')

# Predict
predicted = model.predict(padded_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step


In [24]:
predicted

array([[2.88364190e-05, 2.22993942e-04, 1.38369948e-01, 9.64757130e-02,
        5.87969180e-03, 5.19959405e-02, 4.74274121e-02, 2.55060732e-01,
        4.90742037e-04, 3.12396951e-05, 1.30378653e-03, 3.04813730e-04,
        3.80644546e-04, 1.66524420e-04, 8.15119594e-04, 4.11156914e-04,
        2.67728418e-03, 2.24418964e-05, 1.71090782e-04, 3.92258298e-05,
        2.86592934e-02, 2.87676416e-02, 8.07307754e-03, 2.07338668e-03,
        8.55539227e-04, 1.62737022e-04, 4.05539831e-05, 1.97443020e-04,
        2.43400118e-05, 9.68583772e-05, 4.56990201e-05, 3.15204449e-02,
        1.57076549e-02, 6.35719334e-05, 9.49356181e-04, 6.04377012e-04,
        3.16548918e-04, 5.19369496e-05, 4.81487572e-04, 4.61122072e-05,
        4.65282165e-02, 4.11479808e-02, 2.49784607e-05, 2.89644562e-02,
        2.32410748e-02, 3.32781044e-03, 4.15076938e-05, 5.97851875e-04,
        7.36574060e-04, 5.03608608e-04, 7.50906547e-05, 1.03116610e-04,
        1.79585943e-04, 2.97968625e-04, 1.52115943e-04, 3.485890

In [25]:
import numpy as np
print(np.argmax(predicted))

7


In [26]:
tokenizer.word_index

{'and': 1,
 'data': 2,
 'analysis': 3,
 'a': 4,
 'the': 5,
 'can': 6,
 'is': 7,
 "it's": 8,
 'organizations': 9,
 'to': 10,
 'make': 11,
 'informed': 12,
 'decisions': 13,
 'predict': 14,
 'improve': 15,
 'company': 16,
 'through': 17,
 'customer': 18,
 'strategies': 19,
 'healthcare': 20,
 'not': 21,
 'just': 22,
 'mere': 23,
 'process': 24,
 'tool': 25,
 'that': 26,
 'empowers': 27,
 'trends': 28,
 'operational': 29,
 'efficiency': 30,
 'backbone': 31,
 'of': 32,
 'strategic': 33,
 'planning': 34,
 'in': 35,
 'businesses': 36,
 'governments': 37,
 'other': 38,
 'consider': 39,
 'some': 40,
 'examples': 41,
 'take': 42,
 'for': 43,
 'instance': 44,
 'leading': 45,
 'e': 46,
 'commerce': 47,
 'understand': 48,
 'their': 49,
 "customers'": 50,
 'buying': 51,
 'behavior': 52,
 'preferences': 53,
 'patterns': 54,
 'they': 55,
 'then': 56,
 'use': 57,
 'this': 58,
 'information': 59,
 'personalize': 60,
 'experiences': 61,
 'forecast': 62,
 'sales': 63,
 'optimize': 64,
 'marketing': 65,
 

In [27]:
for word, index in tokenizer.word_index.items():
  if index == np.argmax(predicted):
    print(word)

is


In [28]:
text3= "Data analysis is not just a mere process; it's a tool that empowers organizations to make informed decisions,"

# Tokenizer
token_text3 = tokenizer.texts_to_sequences([text3])[0]

# Padding
padded_text = pad_sequences([token_text3], maxlen=max_len-1, padding='pre')

# Predict
predicted = model.predict(padded_text)

pos = np.argmax(predicted)

for word, index in tokenizer.word_index.items():
  if index == np.argmax(predicted):
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
predict


#### Improvements:
1. Increasing the LSTM units
2. Increasing the Dense layers
3. Increasing the Data
4. Using a pre-treained model on larger corpus of data
5. Hyper parameter optimization